# vim:ft=kitty

## name: Base2Tone Mall Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/Base2Tone-kitty/blob/main/themes/base2tone-mall-dark.conf
## blurb: duotone theme | blue violet - light sky blue


#: The basic colors
foreground #4e3236
background #e7cbcf
foreground #4e3236
selection_background #4e3236
selection_foreground #e7cbcf
#: Cursor colors
cursor #4e3236
cursor_text_color #e7cbcf
#: URL underline color when hovering with mouse

url_color #e5dbff


#: kitty window border colors and terminal bell colors

active_border_color #515053
inactive_border_color #1e1e1f
bell_border_color #855ee8
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #2b2b2c
macos_titlebar_color #2b2b2c


#: Tab bar colors
foreground #4e3236
background #e7cbcf
foreground #4e3236
background #e7cbcf
background #e7cbcf
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)
foreground #4e3236
background #e7cbcf
foreground #4e3236
background #e7cbcf
foreground #4e3236
background #e7cbcf
#: The basic 16 colors

#: black
color0 #3c8276
color8 #2b827c

#: red
color1 #9ec690
color9 #bbcb98

#: green
color2 #58a581
color10 #8dc18e

#: yellow
color3 #1b5c71
color11 #66af87

#: blue
color4 #267076
color12 #acc994

#: magenta
color5 #78b98b
color13 #3a917e

#: cyan
color6 #4b9579
color14 #489f82

#: white
color7 #092b5a
color15 #104869
