#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


def get_quote_desmotivational() -> Dict[str, List[str]]:
    return {
        "pt-br": [
            "Quando a vida te der limões, esfregue-os na cada dela!",
            "A sorte é uma vadia, ela quer te foder.",
            "Quando você pensar que tudo que poderia dar errado já deu errado, você vai descobrir que está errado.",
            "Tudo vai dar errado, da pior forma possível e no pior momento possível.",
            "Até logo e obrigado pelos peixes.",
            "Mantenha o seu patrão rico, os sócios deles ricos, os acionistas ricos e perceba que você continua pobre. É, isso é o capitalismo.",
            "Ninguém existe por um propósito. Ninguém pertence a lugar nenhum. Todo mundo vai morrer. Vem ver TV.",
            "Meu nomo é Giovani Giorjo, mas todo mundo me chama Giorjo.",
            "Existe alguém que está contando com você para lutar em seu lugar, já que nesse guerra não é ele quem vai morrer.",
            "Dá um prato de comida aí, por favor, tô com fome.",
            "Eu não sou um monstro, eu só fiz coisas monstruosas.",
            "Eu não sou um monstro, eu sou apenas um cara tentando se divertir.",
            "Eu sou o rei do mundo!",
            "Eu sou o Batman.",
            "Vai chorar?",
            "Tens que acretires que es o melhor! Posso não ser, mas em minha cabeça eu sou o melhor!",
            "O que não te mata te deixa mais estranho.",
            "Uma rapariga é bom, três raparigas é bom demais. Tu tu tu tu!",
            "Meu coselho tá joando, não é joando, tá joando, não é joando, tá joando, não é joando... Tá joando!",
            "Está tudo bem.",
            "Citroen, creative technologie.",
            "Sr. Presidente, se eu aprendi alguma coisa hoje, é que as vezes você tem que ligar o f*da-se!",
            "Eu vim fazer um anúncio! Shadow o ouriço é um filho da p*ta do car*lho. Ele mij*u na minha esposa!",
            "Parece um bom momento para uma bebida e um discurso frio e calculado com um tom sinistro.",
            "Na hora certa, tudo vai dar errado.",
            "Você não pode mudar o seu passado, mas pode arruinar o seu futuro.",
            "O importante na vida é ter a quem culpar.",
            "Trabalhe enquanto eles ganham dinheiro.",
            "O não você já tem, busque a humilhação.",
            "As vezes é dificil separar a coragem da burrice. E a percistencia da falta do que fazer.",
            "O importante é competir, mas te mato de pancada se você não ganhar.",
            "Sempre que estiver em dúlvida, seja você mesmo. Depois que se lembrar de quem você é, se esforce para não ser você mesmo.",
            "Quem não odeia não tem coração.",
            "É melhor ser amado pelo que você não é do que ser odiado pelo que você é.",
            "Não esquente a cabeça com as derrotas de hoje, amanhã tem muito mais!",
            "Dinheiro não traz felicidade, mas a pobreza não traz nada.",
            "Dias melhores virão, mas não para você.",
            "O segredo do sucesso é desistir antes de tentar.",
            "Não morto abra dentro.",
            "Não há nada na vida que não possa piorar.",
            "O pior de tudo é o silêncio do Olavo de Carvalho.",
            "Pokemon, temos que escraviza-los eu sei!",
            "Yu-gi-oh Masterduel é o melhor jogo de cartas de todos os tempos!",
            "Pokemons tipo dragão são os mais fortes.",
            "Gaste todo o seu dinheiro hoje, o futuro é incerto e provavelmente não vai ser melhor.",
            "Não deixe para amanhã o que você pode fazer depois de amanhã.",
            "Ninguem vai pegar meu telefone!",
            "Pegaram meu telefone.",
            "Make Estados Unidos Great Denovo!",
            "Olha essa oportunidade de negócio que descobri. Não é pirâmide, confia!",
            "Popcorn and ice cream sallers!",
            "Um grande falha da minha formação.",
            "Se você virar jacaré, é problema seu.",
            "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men.",
            "Vai toma no c*.",
						"Já pagou seu imposto hoje?",
						"Já pagou a rachadinha hoje?",
						"Já pagou a propina hoje?",
            "Eu tô cansado chefe.",
            "Toptherm saúde e energia, traz de volta a alegria e é gostoso de tomar.",
            "Só se decepciona quem tem expectativas.",
            "Em idiotas, nós confiamos!",
            "Sempre assine sem ler.",
            "Não pergunte o que o governo pode fazer por você, pergunte quanto de imposto você deve pagar para ele.",
            "E nessa loucura, de dizer que não te quero. Vou negando as aparências, disfarçando as evidências.",
            "As pontas de plastico nos cadarços servem para um propósito terrível.",
            "Uno, dos, tres, quatorce...",
            "Imposto é roubo.",
            "Se comprar não é possuir pirataria não é roubo.",
        ],
        "en": [
            "When life gives you lemons, rub them in her face!",
            "Luck is a bi***, it wants to f*** you.",
            "When you think everything that could go wrong has already gone wrong, you'll find out you're wrong.",
            "Everything will go wrong, in the worst possible way and at the worst possible moment.",
            "So long, and thanks for all the fish.",
            "Keep your boss rich, their partners rich, the shareholders rich, and realize you are still poor. Yeah, that's capitalism.",
            "Nobody exists on purpose. Nobody belongs anywhere. Everybody's gonna die. Come watch TV.",
            "My name is Giovanni Giorgio, but everybody calls me Giorgio.",
            "There is someone counting on you to fight in their place, since in this war it is not them who will die.",
            "Give me a plate of food, please, I'm hungry.",
            "I'm not a monster, I only did monstrous things.",
            "I'm not a monster, I'm just a guy trying to have a good time.",
            "I'm the king of the world!",
            "I'm the queen of the world!",
            "I'm Batman.",
            "Gonna cry?",
            "You have to believe you're the best! I might not be, but in my head I am the best!",
            "What doesn't kill you makes you stranger.",
            "It's fine.",
            "Citroen, creative technologie.",
            "Mr. President, if I've learned one thing today, it's that sometimes you have to not give a f***!",
            "I've come to make an announcement: Shadow the Hedgehog's a bitch-ass motherfucker, he pis*** on my fu***** wife!",
            "Looks like a good moment for a drink and a cold, calculated speech with a sinister tone.",
            "At the right time, everything will go wrong.",
            "You can't change your past, but you can ruin your future.",
            "What matters in life is having someone to blame.",
            "Work while they make money.",
            "You already have the no, go chase the humiliation.",
            "Sometimes it's hard to tell courage from stupidity. And persistence from having nothing better to do.",
            "What matters is competing, but I'll beat you up if you don't win.",
            "Whenever in doubt, be yourself. After you remember who you are, try hard not to be yourself.",
            "Who doesn't hate has no heart.",
            "It's better to be loved for what you're not than hated for what you are.",
            "Don't stress about today's defeats, tomorrow there are many more!",
            "Money doesn't bring happiness, but poverty brings nothing.",
            "Better days will come, but not for you.",
            "The secret to success is quitting before trying.",
            "Don't dead open inside.",
            "There is nothing in life that can't get worse.",
            "The worst of all is Epstein's silence.",
            "Pokemon, we have to enslave them, I know!",
            "Yu-Gi-Oh Master Duel is the best card game of all time!",
            "Dragon-type Pokemon are the strongest.",
            "Spend all your money today, the future is uncertain and probably won't be better.",
            "Don't leave for tomorrow what you can do the day after tomorrow.",
            "Nobody is taking my phone!",
            "They took my phone.",
            "Make America Great Again!",
            "Look at this business opportunity I found. It's not a pyramid scheme, trust me!",
            "Popcorn and ice cream sellers!",
            "A big failure in my education.",
            "If you turn into an alligator, that's your problem.",
            "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men.",
            "This is a country where we speak English.",
            "F*ck your!",
            "I'm tired, boss.",
						"You alread pay your tax today?",
            "One big beautiful bill.",
            "Only those who have expectations get disappointed.",
            "In idiots we trust!",
            "Always sign without reading.",
            "I speak english becouse it's the only language that I know. You speak english becouse it's the only language that I know.",
						"The dream comunists, they live inside of my head.",
						"The dream comunists, they come to me in my bed.",
						"I knew that you have found oil. We are coming to bring democracy to your country.",
            "Don't ask what the country can do for you, ask what you can do for your country. And yes, is go to war.",
            "America is the greatest continen... I mean, country. America is the greatest country of the world.",
            "This is America. Don't catch you slippin' now.",
            "Get your money, Black man.",
            "I just whant to set the world on fire.",
            "Come invade with me, lets invade, lets invade away.",
            "Ivade me to the Afghanistan, let me play among war. Let see what explosions is like on Syria an Iraq.",
            "You must remenber this, a shoot is just a shoot, a bomb is just a bomb. The fundamental things apply, as oil goes by.",
            "That's me in the China, that's me in the Ukraine, losing my rare earths.",
            "America F*CK YEAH!",
            "Oh Dany boy, the oil, the oil are calling.",
            "If purchasing isn't ownership, piracy isn't theft.",
        ],
    }


def get_quote_dicks(user: str, pacote_aleatorio: str) -> Dict[str, List[str]]:
    return {
        "pt-br": [
            "Dica de comando útil do dia: rm -rf / --no-preserve-root",
            "Dica de comando útil do dia: dd if=/dev/zero of=/dev/sda",
            "Dica de comando útil do dia: mkfs.ext4 /dev/sda",
            "Dica de comando útil do dia: yes | rm -rf /",
            "Dica de comando útil do dia: :(){ :|:& };:",
            "Dica de comando útil do dia: yay -Rnsu --noconfirm $(pacman -Qdtq)",
            "Dica de comando útil do dia: yay -Scc --noconfirm",
            "Dica de comando útil do dia: systemctl disable --now NetworkManager",
            "Dica de comando útil do dia: curl -sL https://example.com/install.sh | bash",
            "Dica de comando útil do dia: rm -rf /home/*",
            "Dica de comando útil do dia: chmod -R 777 /",
            "Dica de comando útil do dia: echo \"ALL ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers",
            "Use senhas fortes, como 123456 ou a sua data de nascimento",
						"Instala pacotes Snap, instala!",
            "Eu uso Arch, BTW.",
            "As definições de virus foram atualizadas com sucesso.",
            "Abre esse email, não é um vírus. Confia.",
            "Já atualizou o sistema hoje? Não? Então tá tudo certo.",
            "Clica no arquivo nao_e_virus.exe. Confia.",
            "Você esqueceu de incluir o .env no gitignore, né? Que amadorismo.",
            f"Olha o github desse otário, ele deu push até no .env: https://github.com/{user}",
            "Olha essa base de banco de dados que vazei na internet... eita, acho que ela é sua!",
            "Use senhas fracas, é mais fácil de lembrar e de digitar!",
            "Faça backup dos seus arquivos importantes, mas deixe eles na mesma partição que é mais fácil de acessar quando precisar!",
            "Guarde suas senhas em um arquivo de texto que é mais fácil de acessar quando precisar!",
            "Evite quebra de sistema, não atualize!",
            "Não se preocupe em usar um gerenciador de senhas, é só usar a mesma senha para tudo que é mais fácil de lembrar!",
            "Não se preocupe em usar autenticação de dois fatores, é só usar uma senha fraca que é mais fácil de lembrar!",
            "Pacotes de fontes de terceiros são seguros.",
            "Sempre confie nos blobs binários.",
            "Ler documentação é perda de tempo, é melhor perguntar em fóruns ou no Discord!",
            "Faça backup dos seus certificados e chaves privadas no github.",
            "Usar csv é mais fácil do que usar um banco de dados, mesmo para grandes quantidades de dados!",
            "Firewall é superestimado.",
            f"Encontraram uma vulnerabilidade crítica no pacote {pacote_aleatorio}.",
            "Prefira o Bitlocker ao LUKS.",
            "Padrões fechados são os melhores!",
            "Windows ME é o melhor sistema operacional de todos os tempos!",
            "As Big Techs coletam nossos dados para a nossa seguirança.",
            "Use uma VPN gratuita.",
            "Precisamos zelar pela nossa privacidade e colocar todos nossos dados no Facebook.",
            "Binários baixados pela internet são seguros. Confia.",
            "Seu navegador de internet não precisa ser atualizado.",
            "Use IA, estudar programação é coisa do passado!",
            "Adicione todos os repositórios de terceiros possíveis para ter acesso a mais pacotes!",
            "Pacotes do AUR são os mais seguros e confiáveis!",
            "Execute o script primeiro, leia depois.",
            "Não há nada nas interfaces gráficas e nenhum homem precisa de nada.",
						"Deus odeia Python.",
            "NVidia, vá se f*der!",
            "Bom programadores criam, grandes programadores roubam.",
            "Qua papel de parede bonito, seria uma pena se ele fosse apagado.",
            "Já viu o SMART hoje? Parece que seus discos estão fazendo um barulho estranho.",
            "Quam tem um backup tem todos os bakcups que precisa.",
            "Podemos enviar um virus para qualquer lugar do mundo. Direto para o seu computador da sala de jantar.",
            "Make Java Great Again!",
            "Make C# Great Again!",
            "Make Windows Great Again!",
            "E daí, não sou programador.",
            "Tem um vazamento de memória bem alí.",
            "Se tá funcionando, não mexe!",
            "Seguçanca é uma gaveta trancada, com um bloquinho de notas cheio de senhas.",
            "A porta da geladeira é perfeita para grudar senhas e dados sensíveis.",
            "Olha, um Wi-Fi sem senha. Internet gráts!",
            "Se você virar programador, é problema seu.",
            "O caminho do programador justo é cercado por todas as iniquidades dos idiotas e pela tirania dos bugs.",
            "Eu tenho quatro softwares. Foram quatro C++, ai no quinto eu dei uma fraquejada e veio esse aqui.",
            "Clica em concordo, avança, avança e avança.",
        ],
        "en": [
            "Useful command tip of the day: rm -rf / --no-preserve-root",
            "Useful command tip of the day: dd if=/dev/zero of=/dev/sda",
            "Useful command tip of the day: mkfs.ext4 /dev/sda",
            "Useful command tip of the day: yes | rm -rf /",
            "Useful command tip of the day: :(){ :|:& };:",
            "Useful command tip of the day: yay -Rnsu --noconfirm $(pacman -Qdtq)",
            "Useful command tip of the day: yay -Scc --noconfirm",
            "Useful command tip of the day: systemctl disable --now NetworkManager",
            "Useful command tip of the day: curl -sL https://example.com/install.sh | bash",
            "Useful command tip of the day: chmod -R 777 /",
            "Useful command tip of the day: rm -rf /home/*",
            "Useful command tip of the day: echo \"ALL ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers",
						"Use strong passwords,like 123456 or your birth date."
            "Install Snap packages, install!",
            "I use Arch, BTW.",
            "Virus definitions have been successfully updated.",
            "Open this email, it's not a virus. Trust me.",
            "Have you updated your system today? No? Then everything's fine.",
            "Click on the file not_virus.exe. Trust me.",
            "You forgot to include .env in gitginore, didn't you? Amateurism.",
            f"Look the git hub of this looser, he gave push even in .env: https://github.com/{user}",
            "Look at this database that I leaked on the internet... oops, I think it's yours!",
            "Use weak passwords, it's easier to remember and type!",
            "Back up your important files, but leave them on the same partition so they're easier to access when you need them!",
            "Store your passwords in a text file that's easier to access when you need it!",
            "Avoid system breakage, don't update!",
            "Don't worry about using a password manager, just use the same password for everything that's easier to remember!",
            "Don't worry about using two-factor authentication, just use a weak password that's easier to remember!",
            "Third-party font packages are safe.",
            "Always trust binary blobs.",
            "Reading documentation is a waste of time, it's better to ask in forums or on Discord!",
            "Back up your certificates and private keys on github.",
            "Using csv is easier than using a database, even for large amounts of data!",
            "Firewall is overrated.",
            f"A critical vulnerability was found in package {pacote_aleatorio}.",
            "Prefer Bitlocker over LUKS.",
            "Closed standards are the best!",
            "Windows ME is the best operating system of all time!",
            "Big Techs collect our data for our security.",
            "Use a free VPN.",
            "We need to care about our privacy and put all our data on Facebook.",
            "Binaries downloaded from the internet are safe. Trust me.",
            "Your web browser doesn't need to be updated.",
            "Use AI, studying programming is a thing of the past!",
            "Add all possible third-party repositories to have access to more packages!",
            "AUR packages are the safest and most reliable!",
            "Run the script first, read later.",
            "There is nothing in GUIs and no man needs nothing.",
            "God hate Python.",
						"NVidia, F*CK your!",
            "Good programmers create, great programmers steal.",
            "What a beautiful wallpaper, it would be a shame if it were deleted.",
            "Have you seen the SMART today? It looks like your disks are making a strange noise.",
            "Who has a backup has all the backups they need.",
            "We can send a virus anywhere in the world. Straight to your dining room computer.",
            "Make Java Great Again!",
            "Make C# Great Again!",
            "Make Windows Great Again!",
            "So what, I'm not a programmer.",
            "There's a memory leak right there.",
            "If it ain't broke, don't fix it!",
            "Security is a locked drawer, with a notepad full of passwords.",
            "The fridge door is perfect for sticking passwords and sensitive data.",
            "Look, a Wi-Fi without a password. Free internet!",
            "If you turn into a programmer, that's your problem.",
            "The path of the righteous programmer is beset on all sides by the inequities of idiots and the tyranny of bugs.",
            "I have four softwares. They were four C++, then on the fifth I gave a little slack and this one came out.",
            "Click on agree, next, next and install.",
						"I knew that you have found an nice app. We are coming to bring democracy to your computer.",
        ],
    }


def get_douche_catalog(user: str, pacote_aleatorio: str) -> Tuple[Dict[str, List[str]], Dict[str, List[str]]]:
    return get_quote_desmotivational(), get_quote_dicks(user, pacote_aleatorio)
