# vim:ft=kitty

## name: Base2Tone Mall Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/Base2Tone-kitty/blob/main/themes/base2tone-mall-dark.conf
## blurb: duotone theme | blue violet - light sky blue


#: The basic colors

foreground #c9b3b7
background #301a1e
foreground #c9b3b7
selection_background  #121016


#: Cursor colors

cursor #c9b3b7
cursor_text_color #301a1e


#: URL underline color when hovering with mouse

url_color #e5dbff


#: kitty window border colors and terminal bell colors

active_border_color #515053
inactive_border_color #1e1e1f
bell_border_color #855ee8
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #2b2b2c
macos_titlebar_color #2b2b2c


#: Tab bar colors

foreground #c9b3b7
background #301a1e
foreground #c9b3b7
background #301a1e
background #301a1e
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

foreground #c9b3b7
background #301a1e
foreground #c9b3b7
background #301a1e
foreground #c9b3b7
background #301a1e


#: The basic 16 colors

#: black
color0 #0e1217
color8 #70698a

#: red
color1 #79434b
color9 #d9646e

#: green
color2 #3c4150
color10 #4e5367

#: yellow
color3 #dca590
color11 #dca590

#: blue
color4 #73a4e3
color12 #73a4e3

#: magenta
color5 #a073b6
color13 #c68aed

#: cyan
color6 #73a4e3
color14 #73a4e3

#: white
color7 #aebbcc
color15 #aebbcc
