# vim:ft=kitty

## name: Base2Tone Mall Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/Base2Tone-kitty/blob/main/themes/base2tone-mall-dark.conf
## blurb: duotone theme | blue violet - light sky blue


#: The basic colors

foreground #a6a7ad
background #0d0e14
selection_foreground #a6a7ad
selection_background  #121016


#: Cursor colors

cursor #a6a7ad
cursor_text_color #0d0e14


#: URL underline color when hovering with mouse

url_color #e5dbff


#: kitty window border colors and terminal bell colors

active_border_color #515053
inactive_border_color #1e1e1f
bell_border_color #855ee8
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #2b2b2c
macos_titlebar_color #2b2b2c


#: Tab bar colors

active_tab_foreground #f8fafc
active_tab_background #1e1e1f
inactive_tab_foreground #a2abb3
inactive_tab_background #2b2b2c
tab_bar_background #2b2b2c
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #1e1e1f
mark1_background #936df3
mark2_foreground #1e1e1f
mark2_background #7e8891
mark3_foreground #1e1e1f
mark3_background #479eeb


#: The basic 16 colors

#: black
color0 #15151d
color8 #5f668f

#: red
color1 #8f5768
color9 #8f5768

#: green
color2 #235669
color10 #2a7d95

#: yellow
color3 #d87089
color11 #d87089

#: blue
color4 #2a7d95
color12 #33b8d8

#: magenta
color5 #d87089
color13 #d87089

#: cyan
color6 #33b8d8
color14 #33b8d8

#: white
color7 #b0aaea
color15 #b0aaea
